name: backtome
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.0.0
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.0
  flow_builder: ^0.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  hive: ^2.0.2
  hive_flutter: ^1.0.0
  lint: ^1.5.3
  path_provider: ^2.0.1
  permission_handler: ^6.1.1
  ssh:
    git: https://github.com/billyandco/flutter_ssh.git

dev_dependencies:
  build_runner: ^1.12.2
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
